object Versions {
    const val KOTLIN_VERSION = "1.5.30"
    const val GRADLE_TOOLS = "4.2.2"
    const val COROUTINE_CORE = "1.5.2"
    const val COROUTINE_ANDROID = "1.5.2"
    const val GSON = "2.8.6"
    const val RETROFIT = "2.9.0"
    const val OKHTTP = "4.9.0"
    const val NAVIGATION = "2.3.5"
    const val GLIDE ="4.12.0"
    const val HILT = "2.40"
    const val LIFE_CYCLE = "2.4.0"
    const val PAGING = "3.0.1"
    const val REFRESH_LAYOUT = "1.1.0"
    const val RECYCLER_SELECTION = "1.1.0"
    const val FRAGMENT_KTX = "1.3.6"
}